### ISSUE TITLE
finalMatches being sent when final phase is not enabled

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#104]
The website is getting finalMatches, even if in group phase, please fix

**Comment by Limonadeundco** [comment]
Is it still like that, i did change a few things

**Comment by Limonadeundco** [comment]
@EinEisbxr

**Comment by EinEisbxr** [comment]
Yeah, It is still like this, after some finalMatches are in the database. And if it works correctly, you have to refresh the website after the mode has been changed to "final phase", because nothing is sent in update data

**Comment by Limonadeundco** [comment]
Tried to fix it again, should not be able to send it when not in mode 2

**Comment by EinEisbxr** [comment]
I think you fixed it
