### ISSUE TITLE
update logic for finalMatches broken

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#127]
There are null values, and I dont get updates, when switching modes

**Comment by EinEisbxr** [comment]
Still an issue

**Comment by EinEisbxr** [comment]
When giving goals in a final match, it is not being updated with updated_data

**Comment by EinEisbxr** [comment]
goals are just being updated, when next button is pressed

**Comment by Limonadeundco** [comment]
Fixed, full fix only possible, when #174 is done
