### ISSUE TITLE
The boy with the most goals made get a special website and calculation for Website ln server

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#169]

**Comment by EinEisbxr** [comment]
Add /best_scorer endpoint with data about enabled, and then names and goals and team and stuff

**Comment by EinEisbxr** [comment]
I think, a full table would be good @Limonadeundco. Give me more info about the data

**Comment by EinEisbxr** [comment]
/best_scorer_data: names, goals, place

/update_data: Add info if best_scorer should be activated

**Comment by Limonadeundco** [comment]
Endpoint is ready

**Comment by EinEisbxr** [comment]
> /best_scorer_data: names, goals, place
> 
> /update_data: Add info if best_scorer should be activated

forgot to add status in update_data @Limonadeundco

**Comment by EinEisbxr** [comment]
merged branch
