### ISSUE TITLE
improve the website and programm if there are no teams, so no matches and so on

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#187]

**Comment by Limonadeundco** [comment]
Make sure, that the website / server work even when there are no teams and no matches and so on

**Comment by EinEisbxr** [comment]
wrong, nothing done yet

**Comment by EinEisbxr** [comment]
waiting for issue #203 and #204

**Comment by EinEisbxr** [comment]
after doing #209, this will be done
