### ISSUE TITLE
When the final phase is activated, the Half Final Teams are not shown correctly

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#228]
When the final phase is activated, the Half Final Teams are displayed for a second, but then are overwritten by "???"
![grafik](https://github.com/TechnikAG-HHG/footballtree/assets/117310683/da9ba9ec-bb46-49e8-bdc9-57df1349f753)

**Comment by EinEisbxr** [comment]
cant recreate at the moment, need to fix issue #220 first

**Comment by Limonadeundco** [comment]
Could be fixed through cache changes or by fixing the final matches bug in another issue
