### ISSUE TITLE
i broke the Website logic, because of big changes in best_scorer_data, probably

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#245]

**Comment by Limonadeundco** [comment]
new response: 
`{"players":[{"1":{"goals":4,"playerName":"a 11","teamName":"Team 2"}},{"1":{"goals":4,"playerName":"a 14","teamName":"Team 2"}},{"2":{"goals":2,"playerName":"a 12","teamName":"Team 2"}},{"2":{"goals":2,"playerName":"a 15","teamName":"Team 2"}},{"2":{"goals":2,"playerName":"a 16","teamName":"Team 2"}},{"2":{"goals":2,"playerName":"a 17","teamName":"Team 2"}},{"2":{"goals":2,"playerName":"v 2","teamName":"Team 3"}},{"3":{"goals":1,"playerName":"a 13","teamName":"Team 2"}},{"3":{"goals":1,"playerName":"v 1","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"a","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 1","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 2","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 3","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 4","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 5","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 6","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 7","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 8","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 9","teamName":"Team 1"}},{"4":{"goals":0,"playerName":"a 10","teamName":"Team 2"}},{"4":{"goals":0,"playerName":"v","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"vv","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"v 3","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"v 4","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"v 5","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"v 6","teamName":"Team 3"}},{"4":{"goals":0,"playerName":"v 7","teamName":"Team 3"}}]}
`

**Comment by EinEisbxr** [comment]
@Limonadeundco your json doesn't make any sense: You are sending me the current position of the player two times and you are breaking the website with it
