### ISSUE TITLE
Problem in Match generation: The group splitting is not right

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#265]
A team of group A can play against a team of group B

**Comment by Limonadeundco** [comment]
Ich immediately dir gleich einen

**Comment by Limonadeundco** [comment]
![grafik](https://github.com/TechnikAG-HHG/footballtree/assets/117310683/0c56444d-463a-4055-b516-3e87afc0d95d)

Cant Recreate, please be more precise
